[package]
name = "read-protobuffer"
version = "0.0.0"
authors = ["Albert Nadal Garriga"]
keywords = ["proto3", "read", "protobuffer"]
edition = "2018"

[dependencies]
protobuf = {version = "^2.10.2"}
fsio = "0.1.2"
chrono = "0.4.11"
