<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3/company.proto

if (false) {
    /**
     * This class is deprecated. Use Company\CompanyCategory instead.
     * @deprecated
     */
    class Company_CompanyCategory {}
}
class_exists(Company\CompanyCategory::class);
@trigger_error('Company_CompanyCategory is deprecated and will be removed in the next major release. Use Company\CompanyCategory instead', E_USER_DEPRECATED);

